apiVersion: v1
kind: Namespace
metadata:
  name: todoapp
---
apiVersion: v1
kind: Secret
metadata:
  name: app-db-secret
  namespace: todoapp
type: Opaque
stringData:
  NAME: mydb
  USER: myuser
  PASSWORD: userpass
  HOST: mysql-0.mysql.mysql.svc.cluster.local
